import styles from '@/app/layout.module.css';
import { Outfit } from "next/font/google";
import '../app/styles/globals.css';
import Navbar from './components/navbar';

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Next.js</title> 
      </head>
      <body className={inter.className}>
        <div className={styles.root} >
            <Navbar/>
            <div>
            {children}
            </div>
        </div>
      </body>
    </html>) 
}

        {/* <div className={styles.header}>
            From layout
            <Link href='/pulse-a/about'>About</Link>
            <Link href='/pulse-a/details'>Details</Link>
        </div> */}
